### ISSUE TITLE
Repeat connection error when printer not connected to OctoPrint.

### ISSUE THREAD

**Issue by s1mpleman** [s1mpleman/OctoFarm#1]
Guess it's polling consistently and has no current error checking in place for this.

**Comment by steclarkdev** [comment]
What behavior would you like?

**Comment by s1mpleman** [comment]
I was thinking how to handle this just now. It's going to have to poll the server for sure to find when it actually does connect. I guess the best way would be just make it change the status to "Printer Not Connected" and then ignore any further errors until a connection is made. 

Eventually, if possible I would like to add a button to start a connection which would probably clean that up easier as it doesn't need to poll until that is clicked. For the initial release, I think we should just focus on making it display the status of the printer for now so the above solution should be enough. What do you think?

**Comment by s1mpleman** [comment]
I've got more of the HTML done, and when testing realised it's throwing an issue with `.error(function()`

I tried replacing it with .on("error",function(){} but that didn't work either. Any ideas? Guess these two are related.

**Comment by steclarkdev** [comment]
If you do a checkin, i can take a look later, prob in two hours or so. You most likely have a syntax error somewhere before that.

**Comment by NotExpectYet** [comment]
Sound ill figure out how to do that if I have no look in a bit. Got a bit before bed, might as well try.

**Comment by s1mpleman** [comment]
Reopened as this isn't resolved. 

Just tested with connecting a printer.

**Comment by s1mpleman** [comment]
Merged code from an updated branch that fixes all these errors! Closed :D
